export type BikeDetailedInfo = {
  brand: string,
  model: string,
  year: number,
  size: string,
  stack: number,
  reach: number,
  topTubeLength?: number,
  seatTubeLength?: number,
  seatTubeAngle?: number,
  seatPostLength?: number,
  headTubeAngle?: number,
  chainStay?: number,
  forkRake?: number,
  wheelbase?: number,
  trail?: number,
  bbDrop?: number,
  frontCenterDistance?: number,
  headTubeLength?: number,
  stemLength?: number,
  forkLength?: number,
  standoverHeight?: number,
  wheelSize?: string,
  bodyHeightRange?: string,
  seatHeightRange?: string,
  seatPostDiameter?: string,
}